# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.25.1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.25.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/elenaliarou/Downloads/Polygon-Project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/elenaliarou/Downloads/Polygon-Project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.24.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.25.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/elenaliarou/Downloads/Polygon-Project/CMakeFiles /Users/elenaliarou/Downloads/Polygon-Project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/elenaliarou/Downloads/Polygon-Project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

convexHull.o: convexHull.cpp.o
.PHONY : convexHull.o

# target to build an object file
convexHull.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/convexHull.cpp.o
.PHONY : convexHull.cpp.o

convexHull.i: convexHull.cpp.i
.PHONY : convexHull.i

# target to preprocess a source file
convexHull.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/convexHull.cpp.i
.PHONY : convexHull.cpp.i

convexHull.s: convexHull.cpp.s
.PHONY : convexHull.s

# target to generate assembly for a file
convexHull.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/convexHull.cpp.s
.PHONY : convexHull.cpp.s

edgeChange.o: edgeChange.cpp.o
.PHONY : edgeChange.o

# target to build an object file
edgeChange.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/edgeChange.cpp.o
.PHONY : edgeChange.cpp.o

edgeChange.i: edgeChange.cpp.i
.PHONY : edgeChange.i

# target to preprocess a source file
edgeChange.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/edgeChange.cpp.i
.PHONY : edgeChange.cpp.i

edgeChange.s: edgeChange.cpp.s
.PHONY : edgeChange.s

# target to generate assembly for a file
edgeChange.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/edgeChange.cpp.s
.PHONY : edgeChange.cpp.s

edgePointPair.o: edgePointPair.cpp.o
.PHONY : edgePointPair.o

# target to build an object file
edgePointPair.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/edgePointPair.cpp.o
.PHONY : edgePointPair.cpp.o

edgePointPair.i: edgePointPair.cpp.i
.PHONY : edgePointPair.i

# target to preprocess a source file
edgePointPair.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/edgePointPair.cpp.i
.PHONY : edgePointPair.cpp.i

edgePointPair.s: edgePointPair.cpp.s
.PHONY : edgePointPair.s

# target to generate assembly for a file
edgePointPair.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/edgePointPair.cpp.s
.PHONY : edgePointPair.cpp.s

genericUtil.o: genericUtil.cpp.o
.PHONY : genericUtil.o

# target to build an object file
genericUtil.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/genericUtil.cpp.o
.PHONY : genericUtil.cpp.o

genericUtil.i: genericUtil.cpp.i
.PHONY : genericUtil.i

# target to preprocess a source file
genericUtil.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/genericUtil.cpp.i
.PHONY : genericUtil.cpp.i

genericUtil.s: genericUtil.cpp.s
.PHONY : genericUtil.s

# target to generate assembly for a file
genericUtil.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/genericUtil.cpp.s
.PHONY : genericUtil.cpp.s

geoUtil.o: geoUtil.cpp.o
.PHONY : geoUtil.o

# target to build an object file
geoUtil.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/geoUtil.cpp.o
.PHONY : geoUtil.cpp.o

geoUtil.i: geoUtil.cpp.i
.PHONY : geoUtil.i

# target to preprocess a source file
geoUtil.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/geoUtil.cpp.i
.PHONY : geoUtil.cpp.i

geoUtil.s: geoUtil.cpp.s
.PHONY : geoUtil.s

# target to generate assembly for a file
geoUtil.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/geoUtil.cpp.s
.PHONY : geoUtil.cpp.s

incremental.o: incremental.cpp.o
.PHONY : incremental.o

# target to build an object file
incremental.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/incremental.cpp.o
.PHONY : incremental.cpp.o

incremental.i: incremental.cpp.i
.PHONY : incremental.i

# target to preprocess a source file
incremental.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/incremental.cpp.i
.PHONY : incremental.cpp.i

incremental.s: incremental.cpp.s
.PHONY : incremental.s

# target to generate assembly for a file
incremental.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/incremental.cpp.s
.PHONY : incremental.cpp.s

localSearch.o: localSearch.cpp.o
.PHONY : localSearch.o

# target to build an object file
localSearch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/localSearch.cpp.o
.PHONY : localSearch.cpp.o

localSearch.i: localSearch.cpp.i
.PHONY : localSearch.i

# target to preprocess a source file
localSearch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/localSearch.cpp.i
.PHONY : localSearch.cpp.i

localSearch.s: localSearch.cpp.s
.PHONY : localSearch.s

# target to generate assembly for a file
localSearch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/localSearch.cpp.s
.PHONY : localSearch.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

outputInfo.o: outputInfo.cpp.o
.PHONY : outputInfo.o

# target to build an object file
outputInfo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/outputInfo.cpp.o
.PHONY : outputInfo.cpp.o

outputInfo.i: outputInfo.cpp.i
.PHONY : outputInfo.i

# target to preprocess a source file
outputInfo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/outputInfo.cpp.i
.PHONY : outputInfo.cpp.i

outputInfo.s: outputInfo.cpp.s
.PHONY : outputInfo.s

# target to generate assembly for a file
outputInfo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/outputInfo.cpp.s
.PHONY : outputInfo.cpp.s

simulatedAnnealing.o: simulatedAnnealing.cpp.o
.PHONY : simulatedAnnealing.o

# target to build an object file
simulatedAnnealing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/simulatedAnnealing.cpp.o
.PHONY : simulatedAnnealing.cpp.o

simulatedAnnealing.i: simulatedAnnealing.cpp.i
.PHONY : simulatedAnnealing.i

# target to preprocess a source file
simulatedAnnealing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/simulatedAnnealing.cpp.i
.PHONY : simulatedAnnealing.cpp.i

simulatedAnnealing.s: simulatedAnnealing.cpp.s
.PHONY : simulatedAnnealing.s

# target to generate assembly for a file
simulatedAnnealing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/simulatedAnnealing.cpp.s
.PHONY : simulatedAnnealing.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... convexHull.o"
	@echo "... convexHull.i"
	@echo "... convexHull.s"
	@echo "... edgeChange.o"
	@echo "... edgeChange.i"
	@echo "... edgeChange.s"
	@echo "... edgePointPair.o"
	@echo "... edgePointPair.i"
	@echo "... edgePointPair.s"
	@echo "... genericUtil.o"
	@echo "... genericUtil.i"
	@echo "... genericUtil.s"
	@echo "... geoUtil.o"
	@echo "... geoUtil.i"
	@echo "... geoUtil.s"
	@echo "... incremental.o"
	@echo "... incremental.i"
	@echo "... incremental.s"
	@echo "... localSearch.o"
	@echo "... localSearch.i"
	@echo "... localSearch.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... outputInfo.o"
	@echo "... outputInfo.i"
	@echo "... outputInfo.s"
	@echo "... simulatedAnnealing.o"
	@echo "... simulatedAnnealing.i"
	@echo "... simulatedAnnealing.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

