# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.24.2/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.24.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/elenaliarou/Downloads/Polygon-Project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/elenaliarou/Downloads/Polygon-Project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.24.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.24.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/elenaliarou/Downloads/Polygon-Project/CMakeFiles /Users/elenaliarou/Downloads/Polygon-Project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/elenaliarou/Downloads/Polygon-Project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

edgeChange.o: edgeChange.cpp.o
.PHONY : edgeChange.o

# target to build an object file
edgeChange.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/edgeChange.cpp.o
.PHONY : edgeChange.cpp.o

edgeChange.i: edgeChange.cpp.i
.PHONY : edgeChange.i

# target to preprocess a source file
edgeChange.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/edgeChange.cpp.i
.PHONY : edgeChange.cpp.i

edgeChange.s: edgeChange.cpp.s
.PHONY : edgeChange.s

# target to generate assembly for a file
edgeChange.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/edgeChange.cpp.s
.PHONY : edgeChange.cpp.s

edgePointPair.o: edgePointPair.cpp.o
.PHONY : edgePointPair.o

# target to build an object file
edgePointPair.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/edgePointPair.cpp.o
.PHONY : edgePointPair.cpp.o

edgePointPair.i: edgePointPair.cpp.i
.PHONY : edgePointPair.i

# target to preprocess a source file
edgePointPair.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/edgePointPair.cpp.i
.PHONY : edgePointPair.cpp.i

edgePointPair.s: edgePointPair.cpp.s
.PHONY : edgePointPair.s

# target to generate assembly for a file
edgePointPair.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/edgePointPair.cpp.s
.PHONY : edgePointPair.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

mainFunctions.o: mainFunctions.cpp.o
.PHONY : mainFunctions.o

# target to build an object file
mainFunctions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/mainFunctions.cpp.o
.PHONY : mainFunctions.cpp.o

mainFunctions.i: mainFunctions.cpp.i
.PHONY : mainFunctions.i

# target to preprocess a source file
mainFunctions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/mainFunctions.cpp.i
.PHONY : mainFunctions.cpp.i

mainFunctions.s: mainFunctions.cpp.s
.PHONY : mainFunctions.s

# target to generate assembly for a file
mainFunctions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/mainFunctions.cpp.s
.PHONY : mainFunctions.cpp.s

mainFunctions2.o: mainFunctions2.cpp.o
.PHONY : mainFunctions2.o

# target to build an object file
mainFunctions2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/mainFunctions2.cpp.o
.PHONY : mainFunctions2.cpp.o

mainFunctions2.i: mainFunctions2.cpp.i
.PHONY : mainFunctions2.i

# target to preprocess a source file
mainFunctions2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/mainFunctions2.cpp.i
.PHONY : mainFunctions2.cpp.i

mainFunctions2.s: mainFunctions2.cpp.s
.PHONY : mainFunctions2.s

# target to generate assembly for a file
mainFunctions2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/mainFunctions2.cpp.s
.PHONY : mainFunctions2.cpp.s

utility.o: utility.cpp.o
.PHONY : utility.o

# target to build an object file
utility.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/utility.cpp.o
.PHONY : utility.cpp.o

utility.i: utility.cpp.i
.PHONY : utility.i

# target to preprocess a source file
utility.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/utility.cpp.i
.PHONY : utility.cpp.i

utility.s: utility.cpp.s
.PHONY : utility.s

# target to generate assembly for a file
utility.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/utility.cpp.s
.PHONY : utility.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... edgeChange.o"
	@echo "... edgeChange.i"
	@echo "... edgeChange.s"
	@echo "... edgePointPair.o"
	@echo "... edgePointPair.i"
	@echo "... edgePointPair.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainFunctions.o"
	@echo "... mainFunctions.i"
	@echo "... mainFunctions.s"
	@echo "... mainFunctions2.o"
	@echo "... mainFunctions2.i"
	@echo "... mainFunctions2.s"
	@echo "... utility.o"
	@echo "... utility.i"
	@echo "... utility.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

