# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/media/akis/Ubuntu-Windows1/Uni/4 ετος/Polygon-Project"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/media/akis/Ubuntu-Windows1/Uni/4 ετος/Polygon-Project"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/media/akis/Ubuntu-Windows1/Uni/4 ετος/Polygon-Project/CMakeFiles" "/media/akis/Ubuntu-Windows1/Uni/4 ετος/Polygon-Project/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/media/akis/Ubuntu-Windows1/Uni/4 ετος/Polygon-Project/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

convexHull.o: convexHull.cpp.o

.PHONY : convexHull.o

# target to build an object file
convexHull.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/convexHull.cpp.o
.PHONY : convexHull.cpp.o

convexHull.i: convexHull.cpp.i

.PHONY : convexHull.i

# target to preprocess a source file
convexHull.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/convexHull.cpp.i
.PHONY : convexHull.cpp.i

convexHull.s: convexHull.cpp.s

.PHONY : convexHull.s

# target to generate assembly for a file
convexHull.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/convexHull.cpp.s
.PHONY : convexHull.cpp.s

edgeChange.o: edgeChange.cpp.o

.PHONY : edgeChange.o

# target to build an object file
edgeChange.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/edgeChange.cpp.o
.PHONY : edgeChange.cpp.o

edgeChange.i: edgeChange.cpp.i

.PHONY : edgeChange.i

# target to preprocess a source file
edgeChange.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/edgeChange.cpp.i
.PHONY : edgeChange.cpp.i

edgeChange.s: edgeChange.cpp.s

.PHONY : edgeChange.s

# target to generate assembly for a file
edgeChange.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/edgeChange.cpp.s
.PHONY : edgeChange.cpp.s

edgePointPair.o: edgePointPair.cpp.o

.PHONY : edgePointPair.o

# target to build an object file
edgePointPair.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/edgePointPair.cpp.o
.PHONY : edgePointPair.cpp.o

edgePointPair.i: edgePointPair.cpp.i

.PHONY : edgePointPair.i

# target to preprocess a source file
edgePointPair.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/edgePointPair.cpp.i
.PHONY : edgePointPair.cpp.i

edgePointPair.s: edgePointPair.cpp.s

.PHONY : edgePointPair.s

# target to generate assembly for a file
edgePointPair.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/edgePointPair.cpp.s
.PHONY : edgePointPair.cpp.s

genericUtil.o: genericUtil.cpp.o

.PHONY : genericUtil.o

# target to build an object file
genericUtil.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/genericUtil.cpp.o
.PHONY : genericUtil.cpp.o

genericUtil.i: genericUtil.cpp.i

.PHONY : genericUtil.i

# target to preprocess a source file
genericUtil.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/genericUtil.cpp.i
.PHONY : genericUtil.cpp.i

genericUtil.s: genericUtil.cpp.s

.PHONY : genericUtil.s

# target to generate assembly for a file
genericUtil.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/genericUtil.cpp.s
.PHONY : genericUtil.cpp.s

geoUtil.o: geoUtil.cpp.o

.PHONY : geoUtil.o

# target to build an object file
geoUtil.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/geoUtil.cpp.o
.PHONY : geoUtil.cpp.o

geoUtil.i: geoUtil.cpp.i

.PHONY : geoUtil.i

# target to preprocess a source file
geoUtil.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/geoUtil.cpp.i
.PHONY : geoUtil.cpp.i

geoUtil.s: geoUtil.cpp.s

.PHONY : geoUtil.s

# target to generate assembly for a file
geoUtil.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/geoUtil.cpp.s
.PHONY : geoUtil.cpp.s

incremental.o: incremental.cpp.o

.PHONY : incremental.o

# target to build an object file
incremental.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/incremental.cpp.o
.PHONY : incremental.cpp.o

incremental.i: incremental.cpp.i

.PHONY : incremental.i

# target to preprocess a source file
incremental.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/incremental.cpp.i
.PHONY : incremental.cpp.i

incremental.s: incremental.cpp.s

.PHONY : incremental.s

# target to generate assembly for a file
incremental.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/incremental.cpp.s
.PHONY : incremental.cpp.s

localSearch.o: localSearch.cpp.o

.PHONY : localSearch.o

# target to build an object file
localSearch.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/localSearch.cpp.o
.PHONY : localSearch.cpp.o

localSearch.i: localSearch.cpp.i

.PHONY : localSearch.i

# target to preprocess a source file
localSearch.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/localSearch.cpp.i
.PHONY : localSearch.cpp.i

localSearch.s: localSearch.cpp.s

.PHONY : localSearch.s

# target to generate assembly for a file
localSearch.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/localSearch.cpp.s
.PHONY : localSearch.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

mainUtil.o: mainUtil.cpp.o

.PHONY : mainUtil.o

# target to build an object file
mainUtil.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/mainUtil.cpp.o
.PHONY : mainUtil.cpp.o

mainUtil.i: mainUtil.cpp.i

.PHONY : mainUtil.i

# target to preprocess a source file
mainUtil.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/mainUtil.cpp.i
.PHONY : mainUtil.cpp.i

mainUtil.s: mainUtil.cpp.s

.PHONY : mainUtil.s

# target to generate assembly for a file
mainUtil.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/mainUtil.cpp.s
.PHONY : mainUtil.cpp.s

outputInfo.o: outputInfo.cpp.o

.PHONY : outputInfo.o

# target to build an object file
outputInfo.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/outputInfo.cpp.o
.PHONY : outputInfo.cpp.o

outputInfo.i: outputInfo.cpp.i

.PHONY : outputInfo.i

# target to preprocess a source file
outputInfo.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/outputInfo.cpp.i
.PHONY : outputInfo.cpp.i

outputInfo.s: outputInfo.cpp.s

.PHONY : outputInfo.s

# target to generate assembly for a file
outputInfo.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/outputInfo.cpp.s
.PHONY : outputInfo.cpp.s

runCases.o: runCases.cpp.o

.PHONY : runCases.o

# target to build an object file
runCases.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/runCases.cpp.o
.PHONY : runCases.cpp.o

runCases.i: runCases.cpp.i

.PHONY : runCases.i

# target to preprocess a source file
runCases.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/runCases.cpp.i
.PHONY : runCases.cpp.i

runCases.s: runCases.cpp.s

.PHONY : runCases.s

# target to generate assembly for a file
runCases.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/runCases.cpp.s
.PHONY : runCases.cpp.s

simulatedAnnealing.o: simulatedAnnealing.cpp.o

.PHONY : simulatedAnnealing.o

# target to build an object file
simulatedAnnealing.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/simulatedAnnealing.cpp.o
.PHONY : simulatedAnnealing.cpp.o

simulatedAnnealing.i: simulatedAnnealing.cpp.i

.PHONY : simulatedAnnealing.i

# target to preprocess a source file
simulatedAnnealing.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/simulatedAnnealing.cpp.i
.PHONY : simulatedAnnealing.cpp.i

simulatedAnnealing.s: simulatedAnnealing.cpp.s

.PHONY : simulatedAnnealing.s

# target to generate assembly for a file
simulatedAnnealing.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/simulatedAnnealing.cpp.s
.PHONY : simulatedAnnealing.cpp.s

timeManager.o: timeManager.cpp.o

.PHONY : timeManager.o

# target to build an object file
timeManager.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/timeManager.cpp.o
.PHONY : timeManager.cpp.o

timeManager.i: timeManager.cpp.i

.PHONY : timeManager.i

# target to preprocess a source file
timeManager.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/timeManager.cpp.i
.PHONY : timeManager.cpp.i

timeManager.s: timeManager.cpp.s

.PHONY : timeManager.s

# target to generate assembly for a file
timeManager.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/timeManager.cpp.s
.PHONY : timeManager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... convexHull.o"
	@echo "... convexHull.i"
	@echo "... convexHull.s"
	@echo "... edgeChange.o"
	@echo "... edgeChange.i"
	@echo "... edgeChange.s"
	@echo "... edgePointPair.o"
	@echo "... edgePointPair.i"
	@echo "... edgePointPair.s"
	@echo "... genericUtil.o"
	@echo "... genericUtil.i"
	@echo "... genericUtil.s"
	@echo "... geoUtil.o"
	@echo "... geoUtil.i"
	@echo "... geoUtil.s"
	@echo "... incremental.o"
	@echo "... incremental.i"
	@echo "... incremental.s"
	@echo "... localSearch.o"
	@echo "... localSearch.i"
	@echo "... localSearch.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainUtil.o"
	@echo "... mainUtil.i"
	@echo "... mainUtil.s"
	@echo "... outputInfo.o"
	@echo "... outputInfo.i"
	@echo "... outputInfo.s"
	@echo "... runCases.o"
	@echo "... runCases.i"
	@echo "... runCases.s"
	@echo "... simulatedAnnealing.o"
	@echo "... simulatedAnnealing.i"
	@echo "... simulatedAnnealing.s"
	@echo "... timeManager.o"
	@echo "... timeManager.i"
	@echo "... timeManager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

